apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: metrics
    release: prometheus
  name: oci-queue-exporter
  namespace: metrics
spec:
  endpoints:
  - port: http
    scheme: http
    interval: 30s
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: oci-queue-exporter # The label used in the deployment of the OCI queue exporter