apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
  namespace: default
  labels:
    app: dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - name: echo
          image: hashicorp/http-echo
          args:
            - "-text=Hello from Dummy"
          ports:
            - containerPort: 5678
